import Foundation

// MARK: - Core Data Models (Schema.org compliant)

/// Represents the top-level structure of a recognized menu
struct MenuData: Codable, Equatable {
    let sections: [MenuSection]
    let currency: String
    let languageDetected: String
    let metadata: MenuMetadata
    
    // Helper to flatten items for counting
    var totalItems: Int {
        sections.reduce(0) { $0 + $1.items.count }
    }
}

struct MenuMetadata: Codable, Equatable {
    let restaurantName: String?
    let timestamp: Date
}

/// Represents a physical section on the menu (e.g., "Starters", "Mains")
struct MenuSection: Codable, Identifiable, Equatable {
    var id: String { name }
    let name: String
    let items: [MenuItem]
}

/// A specific dish or drink
struct MenuItem: Codable, Identifiable, Equatable {
    var id: String { originalName }
    
    let originalName: String
    let description: String?
    let price: Double?
    
    // AI-Inferred Attributes
    let isSpicy: Bool
    let isVegetarian: Bool
    let containsGluten: Bool
    let containsPeanuts: Bool
    let containsSeafood: Bool
    
    // For V2: Recommendation Score
    var matchScore: Double? = nil
}

// MARK: - Recommendation Models

struct MenuRecommendation: Codable, Identifiable {
    var id = UUID()
    let recommendedItem: MenuItem
    let translation: CulturalTranslation
    let reasoning: String
    let pairings: [String]? // e.g., Wine pairing
    var imageURL: URL? = nil // Generated by Visualizer Agent
}

struct CulturalTranslation: Codable {
    let localizedName: String // "夫妻肺片" -> "Spicy Beef & Tripe"
    let culturalContext: String // "Served cold, numbing spicy, popular appetizer"
    let warnings: [String] // ["Offal", "High Sodium"]
    let warnings: [String] // ["Offal", "High Sodium"]
}

// MARK: - V2: Individual Profile
struct IndividualProfile: Codable, Equatable {
    var partySize: Int = 1
    var budget: Int = 50
    var allergies: [String] = []
    var tastePreference: String = "Spicy" // "Authentic", "Mild"
}

// MARK: - V2 Group Models

struct GroupProfile: Codable, Equatable {
    var headcount: Int = 4
    var budgetTotal: Int = 200
    var dietaryRestrictions: [String] = [] // "No Pork", "Vegetarian"
    var collectiveAllergies: [String] = [] // "Peanuts"
    var refinementKeywords: [String] = []  // "Seafood", "Fried" (The "Something Else" input)
}

struct ComboRecommendation: Codable, Identifiable {
    var id = UUID()
    let name: String // "The Family Feast"
    let dishes: [MenuItem]
    let drinks: [DrinkRecommendation] // Paired drinks
    let totalPrice: Double
    let reasoning: String
    var imageURL: URL? = nil
}

struct DrinkRecommendation: Codable, Identifiable {
    var id: String { name }
    let name: String
    let type: String // "Alcoholic", "Zero-Proof"
    let description: String
    let pairingReason: String
}
